//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Diagnostics;

namespace WeighBridgeApplication.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        //ApplicationScopedSetting
        //UserScopedSetting
        [UserScopedSetting]
        [DebuggerNonUserCode]
        //[DefaultSettingValue("datasource=localhost;port=3306;Initial Catalog='test';database='ssn_infra';username=root;password=")]
        [DefaultSettingValue("datasource=localhost;Initial Catalog='test';database='bioenable_db';username=root;password=")]
        //[DefaultSettingValue("datasource=192.168.1.10;Initial Catalog='test';database='BioEnable_DB1';username=root;password=")]
        public string ConnectionString
        {
            get
            {
                return (string)this["ConnectionString"];
            }
            set
            {
                this["ConnectionString"] = value;
            }
        }


        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("COM2")]
        public string RFID_1_com_port
        {
            get
            {
                return (string)this["RFID_1_com_port"];
            }
            set
            {
                this["RFID_1_com_port"] = value;
            }
        }




        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("COM3")]
        public string RFID_2_com_port
        {
            get
            {
                return (string)this["RFID_2_com_port"];
            }
            set
            {
                this["RFID_2_com_port"] = value;
            }
        }


        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("COM1")]
        public string com_port
        {
            get
            {
                return (string)this["com_port"];
            }
            set
            {
                this["com_port"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("2400")]
        public string boud_rate
        {
            get
            {
                return (string)this["boud_rate"];
            }
            set
            {
                this["boud_rate"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("8")]
        public string data_bits
        {
            get
            {
                return (string)this["data_bits"];
            }
            set
            {
                this["data_bits"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("1")]
        public string stop_bits
        {
            get
            {
                return (string)this["stop_bits"];
            }
            set
            {
                this["stop_bits"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("None")]
        public string parity
        {
            get
            {
                return (string)this["parity"];
            }
            set
            {
                this["parity"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("PIMPRI CHINCHWAD MUNICIPAL CORPORATION")]
        public string CompanyName
        {
            get
            {
                return (string)this["CompanyName"];
            }
            set
            {
                this["CompanyName"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("C&D Waste Management Plant, Moshi")]
        public string Addressline1
        {
            get
            {
                return (string)this["Addressline1"];
            }
            set
            {
                this["Addressline1"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("BioEnable Technologies Pvt. Ltd.")]
        public string Addressline2
        {
            get
            {
                return (string)this["Addressline2"];
            }
            set
            {
                this["Addressline2"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("False")]
        public bool webServiceCall
        {
            get
            {
                return (bool)this["webServiceCall"];
            }
            set
            {
                this["webServiceCall"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("True")]
        public bool Comportsetting
        {
            get
            {
                return (bool)this["Comportsetting"];
            }
            set
            {
                this["Comportsetting"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("BIO")]
        public string slipString
        {
            get
            {
                return (string)this["slipString"];
            }
            set
            {
                this["slipString"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("http://localhost/SSNweighBridge/homepage.php")]
        public string downloadService
        {
            get
            {
                return (string)this["downloadService"];
            }
            set
            {
                this["downloadService"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("http://localhost/SSNweighBridge/sendData.php")]
        public string uploadService
        {
            get
            {
                return (string)this["uploadService"];
            }
            set
            {
                this["uploadService"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("True")]
        public bool QRcode
        {
            get
            {
                return (bool)this["QRcode"];
            }
            set
            {
                this["QRcode"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("Fully Electronic 60 MT Weighbridge")]
        public string slipMsg
        {
            get
            {
                return (string)this["slipMsg"];
            }
            set
            {
                this["slipMsg"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("False")]
        public bool secondPrint
        {
            get
            {
                return (bool)this["secondPrint"];
            }
            set
            {
                this["secondPrint"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("http://localhost/weighbridge/backupProcess.php")]
        public string backupservice
        {
            get
            {
                return (string)this["backupservice"];
            }
            set
            {
                this["backupservice"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("http://localhost/weighbridge/exportData.php")]
        public string exportdata
        {
            get
            {
                return (string)this["exportdata"];
            }
            set
            {
                this["exportdata"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("D:/SSN_Weighbridge_Backup/SSN")]
        public string backuppath
        {
            get
            {
                return (string)this["backuppath"];
            }
            set
            {
                this["backuppath"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("http://localhost/weighbridge/getUser.php")]
        public string getUser
        {
            get
            {
                return (string)this["getUser"];
            }
            set
            {
                this["getUser"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin1234")]
        public string devicePass
        {
            get
            {
                return (string)this["devicePass"];
            }
            set
            {
                this["devicePass"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.100")]
        public string deviceIP
        {
            get
            {
                return (string)this["deviceIP"];
            }
            set
            {
                this["deviceIP"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin")]
        public string deviceUserID
        {
            get
            {
                return (string)this["deviceUserID"];
            }
            set
            {
                this["deviceUserID"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("8000")]
        public string devicePort
        {
            get
            {
                return (string)this["devicePort"];
            }
            set
            {
                this["devicePort"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("31")]
        public int cctvChanel1
        {
            get
            {
                return (int)this["cctvChanel1"];
            }
            set
            {
                this["cctvChanel1"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("32")]
        public int cctvChanel2
        {
            get
            {
                return (int)this["cctvChanel2"];
            }
            set
            {
                this["cctvChanel2"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("33")]
        public int cctvChanel3
        {
            get
            {
                return (int)this["cctvChanel3"];
            }
            set
            {
                this["cctvChanel3"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.202")]
        public string rfidip1
        {
            get
            {
                return (string)this["rfidip1"];
            }
            set
            {
                this["rfidip1"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("100")]
        public string rfidport1
        {
            get
            {
                return (string)this["rfidport1"];
            }
            set
            {
                this["rfidport1"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.203")]
        public string rfidip2
        {
            get
            {
                return (string)this["rfidip2"];
            }
            set
            {
                this["rfidip2"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("100")]
        public string rfidport2
        {
            get
            {
                return (string)this["rfidport2"];
            }
            set
            {
                this["rfidport2"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("1")]
        public string weighbridgeid
        {
            get
            {
                return (string)this["weighbridgeid"];
            }
            set
            {
                this["weighbridgeid"] = value;
            }
        }


        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("1")]
        public string WB_Name
        {
            get
            {
                return (string)this["WB_Name"];
            }
            set
            {
                this["WB_Name"] = value;
            }
        }

        /////////////////CAMERA SETTINGS/////////////////
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin1234")]
        public string camera1Pass
        {
            get
            {
                return (string)this["camera1Pass"];
            }
            set
            {
                this["camera1Pass"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.100")]
        public string camrea1IP
        {
            get
            {
                return (string)this["camrea1IP"];
            }
            set
            {
                this["camrea1IP"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin")]
        public string camera1UserID
        {
            get
            {
                return (string)this["camera1UserID"];
            }
            set
            {
                this["camera1UserID"] = value;
            }
        }

        //[UserScopedSetting]
        //[DebuggerNonUserCode]
        //[DefaultSettingValue("8000")]
        //public string camera1Port
        //{
        //    get
        //    {
        //        return (string)this["camera1Port"];
        //    }
        //    set
        //    {
        //        this["camera1Port"] = value;
        //    }
        //}

        //[UserScopedSetting]
        //[DebuggerNonUserCode]
        //[DefaultSettingValue("31")]
        //public int camrea1Chanel
        //{
        //    get
        //    {
        //        return (int)this["camrea1Chanel"];
        //    }
        //    set
        //    {
        //        this["camrea1Chanel"] = value;
        //    }
        //}

        /////////CAMERA 2/////////////
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin1234")]
        public string camera2Pass
        {
            get
            {
                return (string)this["camera2Pass"];
            }
            set
            {
                this["camera2Pass"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.100")]
        public string camrea2IP
        {
            get
            {
                return (string)this["camrea2IP"];
            }
            set
            {
                this["camrea2IP"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin")]
        public string camera2UserID
        {
            get
            {
                return (string)this["camera2UserID"];
            }
            set
            {
                this["camera2UserID"] = value;
            }
        }

        //[UserScopedSetting]
        //[DebuggerNonUserCode]
        //[DefaultSettingValue("8000")]
        //public string camera2Port
        //{
        //    get
        //    {
        //        return (string)this["camera2Port"];
        //    }
        //    set
        //    {
        //        this["camera2Port"] = value;
        //    }
        //}

        //[UserScopedSetting]
        //[DebuggerNonUserCode]
        //[DefaultSettingValue("31")]
        //public int camrea2Chanel
        //{
        //    get
        //    {
        //        return (int)this["camrea2Chanel"];
        //    }
        //    set
        //    {
        //        this["camrea2Chanel"] = value;
        //    }
        //}


        ////////////CAMERA3///////////////
        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("admin1234")]
        public string camera3Pass
        {
            get
            {
                return (string)this["camera3Pass"];
            }
            set
            {
                this["camera3Pass"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.100")]
        public string camrea3IP
        {
            get
            {
                return (string)this["camrea3IP"];
            }
            set
            {
                this["camrea3IP"] = value;
            }
        }

        //[UserScopedSetting]
        //[DebuggerNonUserCode]
        //[DefaultSettingValue("admin")]
        //public string camera3UserID
        //{
        //    get
        //    {
        //        return (string)this["camera3UserID"];
        //    }
        //    set
        //    {
        //        this["camera3UserID"] = value;
        //    }
        //}

        //[UserScopedSetting]
        //[DebuggerNonUserCode]
        //[DefaultSettingValue("8000")]
        //public string camera3Port
        //{
        //    get
        //    {
        //        return (string)this["camera3Port"];
        //    }
        //    set
        //    {
        //        this["camera3Port"] = value;
        //    }
        //}

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("31")]
        public int camrea3Chanel
        {
            get
            {
                return (int)this["camrea3Chanel"];
            }
            set
            {
                this["camrea3Chanel"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("1")]
        public int WeighBridgeReaderid
        {
            get
            {
                return (int)this["WeighBridgeReaderid"];
            }
            set
            {
                this["WeighBridgeReaderid"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("MSW Moshi Plant")]
        public string WeighBridgeName
        {
            get
            {
                return (string)this["WeighBridgeName"];
            }
            set
            {
                this["WeighBridgeName"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("192.168.1.106")]
        public string MQTT_Server_IP
        {
            get
            {
                return (string)this["MQTT_Server_IP"];
            }
            set
            {
                this["MQTT_Server_IP"] = value;
            }
        }

        [UserScopedSetting]
        [DebuggerNonUserCode]
        [DefaultSettingValue("WB1")]
        public string WeighBridgeMQTTID
        {
            get
            {
                return (string)this["WeighBridgeMQTTID"];
            }
            set
            {
                this["WeighBridgeMQTTID"] = value;
            }
        }
        

        

       


    }
}
